export const Lang = {
    en: {
        START_GAME: 'START GAME',
        HIGH_SCORE: 'High Score',
        VOLUME: 'Volume',
        SELECT_DIFFICULTY: 'Select Difficulty:',
        GAME_OVER: 'GAME OVER\nPress R to Restart',
        PAUSE: 'PAUSE',
        PAUSE_SUB: 'Press any key to continue',
        LEVEL_UP: 'LEVEL UP!',
        CHOOSE_UPGRADE: 'Choose an upgrade:',
        LEVEL: 'Level',
        AMMO: 'Ammo',
        SCORE: 'Score',
        RELOADING: 'RELOADING...',
        COMBO: 'COMBO',
        SKILL_RAPID_FIRE: 'Rapid Fire',
        SKILL_RAPID_FIRE_DESC: 'Fire Rate +15%',
        SKILL_SPEED_BOOTS: 'Speed Boots',
        SKILL_SPEED_BOOTS_DESC: 'Move Speed +10%',
        SKILL_TITAN_HEALTH: 'Titan Health',
        SKILL_TITAN_HEALTH_DESC: 'Max HP +20',
        SKILL_WEAPON_SHOTGUN: 'Shotgun',
        SKILL_WEAPON_SHOTGUN_DESC: 'Weapon: Spread Shot',
        SKILL_WEAPON_LASER: 'Laser Beam',
        SKILL_WEAPON_LASER_DESC: 'Weapon: Piercing Beam',
        SKILL_WEAPON_RICOCHET: 'Ricochet',
        SKILL_WEAPON_RICOCHET_DESC: 'Weapon: Bouncing Bullets',
        SKILL_ABILITY_TIME_SLOW: 'Time Slow',
        SKILL_ABILITY_TIME_SLOW_DESC: 'Ability (Q): Slow Motion',
        SKILL_ABILITY_NOVA: 'Nova Blast',
        SKILL_ABILITY_NOVA_DESC: 'Ability (Q): Area Blast',
        BOSS_WARNING: 'LEVEL UP: ENEMIES FASTER!',
        DIFF_EASY: 'Easy',
        DIFF_NORMAL: 'Normal',
        DIFF_HARDCORE: 'Hardcore'
    },
    ru: {
        START_GAME: 'НАЧАТЬ ИГРУ',
        HIGH_SCORE: 'Рекорд',
        VOLUME: 'Громкость',
        SELECT_DIFFICULTY: 'Выберите сложность:',
        GAME_OVER: 'ИГРА ОКОНЧЕНА\nНажмите R для рестарта',
        PAUSE: 'ПАУЗА',
        PAUSE_SUB: 'Нажмите любую клавишу',
        LEVEL_UP: 'НОВЫЙ УРОВЕНЬ!',
        CHOOSE_UPGRADE: 'Выберите улучшение:',
        LEVEL: 'Уровень',
        AMMO: 'Патроны',
        SCORE: 'Счет',
        RELOADING: 'ПЕРЕЗАРЯДКА...',
        COMBO: 'КОМБО',
        SKILL_RAPID_FIRE: 'Скорострельность',
        SKILL_RAPID_FIRE_DESC: 'Темп стрельбы +15%',
        SKILL_SPEED_BOOTS: 'Скороходы',
        SKILL_SPEED_BOOTS_DESC: 'Скорость бега +10%',
        SKILL_TITAN_HEALTH: 'Здоровье Титана',
        SKILL_TITAN_HEALTH_DESC: 'Макс. HP +20',
        SKILL_WEAPON_SHOTGUN: 'Дробовик',
        SKILL_WEAPON_SHOTGUN_DESC: 'Оружие: Выстрел веером',
        SKILL_WEAPON_LASER: 'Лазер',
        SKILL_WEAPON_LASER_DESC: 'Оружие: Пробивающий луч',
        SKILL_WEAPON_RICOCHET: 'Рикошет',
        SKILL_WEAPON_RICOCHET_DESC: 'Оружие: Отскок от стен',
        SKILL_ABILITY_TIME_SLOW: 'Замедление',
        SKILL_ABILITY_TIME_SLOW_DESC: 'Способность (Q): Слоу-мо',
        SKILL_ABILITY_NOVA: 'Сверхновая',
        SKILL_ABILITY_NOVA_DESC: 'Способность (Q): Взрыв вокруг',
        BOSS_WARNING: 'УРОВЕНЬ ПОВЫШЕН: ВРАГИ БЫСТРЕЕ!',
        DIFF_EASY: 'Легко',
        DIFF_NORMAL: 'Норма',
        DIFF_HARDCORE: 'Хардкор'
    }
};

export function getTrans(key) {
    // GameState must be imported where needed, or we assume global availability,
    // but to avoid circular dependency with Config.js (if Config imports Lang), 
    // we might need to pass the lang or rely on a global.
    // However, Config.js defines GameState. 
    // Let's just export the dictionary and handle lookup in scenes.
    return Lang;
}
